baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Dev Blogs'
theme = 'smigle'
params.description ='my personal dev posts'
params.author='vimal athithya'


[caches]
  [caches.images]
    dir = ':cacheDir/images'
    maxAge = "800h" 
